name: Deploy to Forge
description: Deploy a release to Laravel Forge

inputs:
  organization:
    required: true
    description: You can find this in the url (https://forge.laravel.com/example-company)

  apiToken:
    required: true
    description: https://forge.laravel.com/profile/api -> create token > 'site:create' + 'site:manage-deploys'

  stagingServerId:
    required: false
    description: The 'Server ID' of the staging server, eg 123456

  stagingSiteId:
    required: false
    description: The 'Site ID' of the staging site, eg 123456

  productionServerId:
    required: false
    description: The 'Server ID' of the production server, eg 123456

  productionSiteId:
    required: false
    description: The 'Site ID' of the production site, eg 123456

runs:
  using: composite
  steps:
    - name: Prepare Forge deployment
      shell: bash
      env:
        FORGE_ORGANIZATION: ${{ inputs.organization }}
        FORGE_API_TOKEN: ${{ inputs.apiToken }}

        RELEASE_ACTION: ${{ github.event.action }}
        IS_PRERELEASE: ${{ github.event.release.prerelease }}
        TAG: ${{ github.event.release.tag_name }}

        FORGE_STG_SERVER_ID: ${{ inputs.stagingServerId }}
        FORGE_STG_SITE_ID: ${{ inputs.stagingSiteId }}
        FORGE_PRD_SERVER_ID: ${{ inputs.productionServerId }}
        FORGE_PRD_SITE_ID: ${{ inputs.productionSiteId }}
      run: |
        if [[ "$RELEASE_ACTION" == "published" && "$IS_PRERELEASE" == "true" ]]; then
          forge_server_id="$FORGE_STG_SERVER_ID"
          forge_site_id="$FORGE_STG_SITE_ID"
          echo "Deploying to Staging (tag: $TAG)"
        elif [[ "$IS_PRERELEASE" == "false" ]]; then
          forge_server_id="$FORGE_PRD_SERVER_ID"
          forge_site_id="$FORGE_PRD_SITE_ID"
          echo "Deploying to Production (tag: $TAG)"
        fi

        if [[ -z "$forge_server_id" || -z "$forge_site_id" ]]; then
          echo "Missing Forge server or site ID for this release"
          exit 1
        fi

        echo "SITE_URL=https://forge.laravel.com/api/orgs/$FORGE_ORGANIZATION/servers/$forge_server_id/sites/$forge_site_id" >> "$GITHUB_ENV"

    - name: Update Forge's branch to the proper tag
      shell: bash
      env:
        FORGE_API_TOKEN: ${{ inputs.apiToken }}
      run: |
        curl \
          --fail-with-body --show-error \
          --request PUT \
          --header "Authorization: Bearer $FORGE_API_TOKEN" \
          --header "Accept: application/json" \
          --header "Content-Type: application/json" \
          --data "$(jq -n --arg tag "${{ github.event.release.tag_name }}" '{repository_branch: $tag}')" \
          "$SITE_URL"

    - name: Trigger Forge deployment
      shell: bash
      env:
        FORGE_API_TOKEN: ${{ inputs.apiToken }}
      run: |
        curl \
          --fail-with-body --show-error \
          --request POST \
          --header "Authorization: Bearer $FORGE_API_TOKEN" \
          --header "Accept: application/json" \
          --header "Content-Type: application/json" \
          "$SITE_URL/deployments"
