name: Deploy to Forge
description: Deploy a release to Laravel Forge

inputs:
  stagingServerId:
    required: false
    description:

  stagingSiteId:
    required: false
    description:

  productionServerId:
    required: false
    description:

  productionSiteId:
    required: false
    description:

  organization:
    required: true
    description:

  apiToken:
    required: true
    description:

runs:
  using: composite
  steps:
      - name: Prepare deploying to STAGING
        if: ${{ github.event.action == 'published' && github.event.release.prerelease == true }}
        env:
          FORGE_STG_SERVER_ID: ${{ inputs.stagingServerId }}
          FORGE_STG_SITE_ID: ${{ inputs.stagingSiteId }}
        run: |
          echo "FORGE_SERVER_ID=$FORGE_STG_SERVER_ID" >> "$GITHUB_ENV"
          echo "FORGE_SITE_ID=$FORGE_STG_SITE_ID" >> "$GITHUB_ENV"

      - name: Prepare deploying to PRODUCTION
        if: ${{ github.event.release.prerelease == false }}
        env:
          FORGE_PRD_SERVER_ID: ${{ inputs.productionServerId }}
          FORGE_PRD_SITE_ID: ${{ inputs.productionSiteId }}
        run: |
          echo "FORGE_SERVER_ID=$FORGE_PRD_SERVER_ID" >> "$GITHUB_ENV"
          echo "FORGE_SITE_ID=$FORGE_PRD_SITE_ID" >> "$GITHUB_ENV"

      - name: Build the Forge SITE_URL
        env:
          FORGE_ORGANIZATION: ${{ inputs.organization }}
        run: |
          if [ -z "$FORGE_SERVER_ID" ] || [ -z "$FORGE_SITE_ID" ]; then
            echo "Missing FORGE_SERVER_ID or FORGE_SITE_ID"
            exit 1
          fi

          echo "SITE_URL=https://forge.laravel.com/api/orgs/$FORGE_ORGANIZATION/servers/$FORGE_SERVER_ID/sites/$FORGE_SITE_ID" >> "$GITHUB_ENV"

      - name: Update Forge's branch to the proper tag
        env:
          FORGE_API_TOKEN: ${{ inputs.apiToken }}
        run: |
          curl \
            --fail-with-body --show-error \
            --request PUT \
            --header "Authorization: Bearer $FORGE_API_TOKEN" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data "$(jq -n --arg tag "${{ github.event.release.tag_name }}" '{repository_branch: $tag}')" \
            "$SITE_URL"

      - name: Trigger Forge deployment
        run: |
          curl \
            --fail-with-body --show-error \
            --request POST \
            --header "Authorization: Bearer $FORGE_API_TOKEN" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            "$SITE_URL/deployments"
